#global:
#  scrape_interval: 15s
#
#scrape_configs:
#  - job_name: 'spring-boot-app'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['pharma-app:8080']  # ou le nom de ton service Docker
